# This is a basic workflow to help you get started with Actions

name: Github Actions Maven Build Example

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: step1 - check out from my github repository
        uses: actions/checkout@v2

      - name: step2 - set up jdk 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: step3 - package project
        run: mvn -B package --file pom.xml
        
      - name: step4 - check
        run: |
          pwd
          ls -ltra
          ls -ltra target
      
      - name: step5 - clean and package project
        run: mvn clean package
        
      - name: step6 - check
        run: |
          pwd
          ls -ltra
          ls -ltra target
        
        
        
       
